[keyboard]
name = "PISIC"
vendor_id = 0xF00D
product_id = 0x6211
manufacturer = "yuburoll"
product_name = "PISIC"
serial_number = "vial:f64c2b3c"
chip = "nrf52840"
usb_enable = true

[features]
nfc-pins-as-gpio = ["P0_09", "P0_10"]

[rmk]
ble_profiles_num = 3
split_peripherals_num = 2

[ble]
enabled = true
battery_adc_pin = "vddh"

[split]
connection = "ble"

[split.central] # dongle
rows = 0
cols = 0
row_offset = 0
col_offset = 0
[split.central.matrix]
matrix_type = "normal"
row_pins = []
col_pins = []
row2col = false

[[split.peripheral]] # left
rows = 4
cols = 6
row_offset = 0
col_offset = 0
[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P1_13", "P1_11", "P0_10", "P0_09"]
col_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
row2col = false

[[split.peripheral]] # right
rows = 4
cols = 6
row_offset = 0
col_offset = 6
[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P1_13", "P1_11", "P0_10", "P0_09"]
col_pins = ["P1_06", "P1_04", "P0_11", "P1_00", "P0_24", "P0_22"]
row2col = false

[behavior.morse]
hold_on_other_press = true
hold_timeout = "200ms"
[behavior.morse.profiles]
PERM = {permissive_hold = true} 
NORM = {normal_mode = true}

[layout]
rows = 4
cols = 12
layers = 8
matrix_map = """
    (0, 0, L)       (0, 1, L)       (0, 2, L)       (0, 3, L)       (0, 4, L)       (0, 5, L)       (0, 6, R)       (0, 7, R)       (0, 8, R)       (0, 9, R)       (0,10, R)       (0,11, R)
            (1, 0, L)       (1, 1, L)       (1, 2, L)       (1, 3, L)       (1, 4, L)                       (1, 7, R)       (1, 8, R)       (1, 9, R)       (1,10, R)       (1,11, R)
    (2, 0, L)       (2, 1, L)       (2, 2, L)       (2, 3, L)       (2, 4, L)       (2, 5, L)       (2, 6, R)       (2, 7, R)       (2, 8, R)       (2, 9, R)       (2,10, R)       (2,11, R)
    (3, 0, L)       (3, 1, L)                       (3, 3, L)       (3, 4, L)       (3, 5, L)       (3, 6, R)       (3, 7, R)       (3, 8, R)                       (3,10, R)       (3,11, R)
"""

[[layer]] # Layer 0
name = "base"
keys = """
    Q               W               E               R               T               Y               Y               U               I               O               P               bspc
            A               S               D               F               G                               H               J               K               L               scln
    lsft            Z               X               C               V               B               B               N               M               comm            dot             MT(slsh,rshift)
    lctl            lgui                            lalt            del             spc             LT(1,ent,PERM)  ralt            lctl                            LT(2,menu,PERM) LT(1,del,PERM)
"""

[[layer]] # Layer 1
name = "symbol"
keys = """
    1               2               3               4               5               6               7               8               9               0               mins            eql
            tab             esc             grv             no              no                              lbrc            rbrc            up               quot            scln
    _               caps            no              no              no              no              slsh            bsls            left            down            rght            rsft
    _               _                               _               _               _               _               _               ralt                            MO(3)           _
"""

[[layer]] # Layer 2
name = "fn"
keys = """
    F1              F2              F3              F10             F4              F5              F7              F8              F9              F10             F11             F12
            home            end             pgup            pgdn            ins                            no               ms_whlu         ms_up           ms_whll         ms_whlr
    _               no              no              pscr            scrl            brk             no              ms_whld         ms_left         ms_down         ms_right        rctl
    _               _                               _               _               _               ms_btn1         ms_btn3         ms_btn2                         _               no
"""

[[layer]] # Layer 3
name = "mk"
keys = """
    no              no              no              no              no              no              no              no              no              no              no              no
            User0           User1           User2           User5           User6                           no              no              no              no              no
    _               no              no              no              no              no              no              no              no              no              no              no
    no              no                              no              no              no              no              no              no                              _               no
"""

[host]
vial_enabled = true
unlock_keys = [[0, 0], [0, 11]]
